version: '3.8'

services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules 
    command: npm run start
