services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_application
    command: tail -f /dev/null
    working_dir: /usr/app
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/usr/app

  db:
    image: mysql:8.0
    container_name: database_application
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    env_file:
      - .env
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local
